// ============================================================
// BARDIFY — Shakespeare lexicon & corpus data
// All quotes, insult fragments, and vocabulary are drawn from
// Shakespeare's plays and sonnets (public domain).
// ============================================================

// ---------- Modern -> Shakespearean: multi-word phrases (checked first) ----------
export const PHRASES_M2S = [
  ["how are you", "how dost thou fare"],
  ["how's it going", "how goes the world with thee"],
  ["how is it going", "how goes the world with thee"],
  ["what's up", "what news on the Rialto"],
  ["what is up", "what news on the Rialto"],
  ["oh my god", "by heaven"],
  ["oh my gosh", "by my troth"],
  ["good morning", "good morrow"],
  ["good evening", "good even"],
  ["good night", "good night, good night! parting is such sweet sorrow"],
  ["see you later", "we shall meet anon"],
  ["see you soon", "we shall meet anon"],
  ["right now", "presently"],
  ["right away", "with all convenient speed"],
  ["a lot of", "a plenitude of"],
  ["lots of", "a plenitude of"],
  ["i think", "methinks"],
  ["i thought", "methought"],
  ["it seems to me", "methinks"],
  ["i don't know", "i wot not"],
  ["i do not know", "i wot not"],
  ["shut up", "hold thy tongue"],
  ["be quiet", "peace, hold thy tongue"],
  ["go away", "avaunt, and quit my sight"],
  ["get out", "avaunt, and quit my sight"],
  ["leave me alone", "avaunt, and leave me to my thoughts"],
  ["i'm sorry", "i cry thee mercy"],
  ["i am sorry", "i cry thee mercy"],
  ["excuse me", "i cry thee mercy"],
  ["thank you very much", "i thank thee with all my heart"],
  ["thanks a lot", "gramercy, a thousand times"],
  ["thank you", "i give thee thanks"],
  ["you're welcome", "thou art most welcome"],
  ["no way", "it cannot be, and yet 'tis so"],
  ["for real", "in sooth"],
  ["i swear", "by my troth"],
  ["i promise", "i plight thee my troth"],
  ["listen up", "lend me your ears"],
  ["check it out", "but look, where it comes"],
  ["hurry up", "hie thee hither with all speed"],
  ["calm down", "be not so hot"],
  ["chill out", "be not so hot"],
  ["hang out", "keep company"],
  ["hang on", "soft you now"],
  ["wait a minute", "soft you now, a word or two"],
  ["hold on", "soft you now"],
  ["of course", "aye, marry"],
  ["let's go", "come, away"],
  ["let us go", "come, away"],
  ["good luck", "fortune smile upon thee"],
  ["best friend", "bosom companion"],
  ["boyfriend", "gentleman-suitor"],
  ["girlfriend", "lady-love"],
  ["in trouble", "in a parlous state"],
  ["freak out", "fall into a fit of madness"],
  ["freaked out", "fell into a fit of madness"],
  ["i love you", "i do love nothing in the world so well as you"],
  ["i hate you", "thou art mine enemy, and i do defy thee"],
  ["are you serious", "speak'st thou in sober earnest"],
  ["are you kidding", "dost thou jest"],
  ["just kidding", "i did but jest"],
  ["make fun of", "flout"],
  ["a little bit", "a whit"],
  ["a little", "a whit"],
  ["too bad", "the more the pity"],
  ["that's crazy", "o day and night, but this is wondrous strange"],
  ["so cool", "most wondrous"],
  ["very good", "passing good"],
  ["really good", "passing good"],
  ["very bad", "most foul"],
  ["really bad", "most foul"],
  ["as soon as possible", "with all convenient speed"],
  ["cell phone", "enchanted speaking-glass"],
  ["cellphone", "enchanted speaking-glass"],
  ["phone", "speaking-glass"],
  ["computer", "thinking-engine"],
  ["laptop", "lap-borne thinking-engine"],
  ["internet", "the great web of all knowledge"],
  ["social media", "the town crier's endless scroll"],
  ["text me", "dispatch thy letters to me"],
  ["text message", "hasty missive"],
  ["email", "letter borne by lightning"],
  ["selfie", "self-wrought portrait"],
  ["car", "horseless carriage"],
  ["tv", "moving picture-frame"],
  ["television", "moving picture-frame"],
  ["video", "moving portrait"],
  ["movie", "moving-picture play"],
  ["homework", "scholar's burden"],
  ["money", "ducats"],
  ["dollars", "ducats"],
  ["bucks", "ducats"],
  ["eat pizza", "feast upon a most savory tart of Naples"],
  ["a pizza", "a most savory tart of Naples"],
  ["the pizza", "the most savory tart of Naples"],
  ["pizza", "savory tart of Naples"],
  ["coffee", "the bitter draught of wakefulness"],
];

// ---------- Modern -> Shakespearean: single words ----------
export const WORDS_M2S = {
  "hello": "good morrow", "hi": "good morrow", "hey": "how now",
  "goodbye": "fare thee well", "bye": "fare thee well",
  "yes": "aye", "yeah": "aye", "yep": "aye, marry",
  "no": "nay", "nope": "nay",
  "please": "prithee", "maybe": "perchance", "perhaps": "perchance",
  "certainly": "certes", "definitely": "certes", "truly": "verily",
  "really": "verily", "very": "most", "totally": "wholly",
  "awesome": "wondrous", "amazing": "wondrous", "cool": "most excellent",
  "great": "passing fine", "nice": "goodly", "beautiful": "beauteous",
  "pretty": "comely", "handsome": "well-favoured", "cute": "winsome",
  "ugly": "ill-favoured", "gross": "loathsome", "nasty": "rank",
  "weird": "passing strange", "crazy": "moon-mad",
  "insane": "lunatic", "stupid": "clay-brained", "dumb": "beef-witted",
  "idiot": "clotpole", "fool": "gudgeon", "jerk": "knave",
  "man": "gentleman", "dude": "good sirrah", "guy": "fellow",
  "woman": "gentlewoman", "girl": "maiden", "boy": "lad",
  "friend": "good coz", "friends": "boon companions", "buddy": "coz",
  "enemy": "foe", "stranger": "unknown wight",
  "quickly": "apace", "fast": "swift", "slowly": "by slow degrees",
  "soon": "anon", "later": "hereafter", "now": "presently",
  "today": "this day", "tonight": "this night", "tomorrow": "on the morrow",
  "yesterday": "yesternight", "always": "evermore", "never": "ne'er",
  "ever": "e'er", "often": "oft", "sometimes": "now and anon",
  "before": "ere", "between": "betwixt", "nothing": "naught",
  "anything": "aught", "something": "somewhat", "almost": "well-nigh",
  "here": "here", "there": "yonder", "away": "hence",
  "listen": "hark", "look": "behold", "wait": "stay",
  "stop": "hold", "leave": "depart", "come": "come hither",
  "go": "get thee gone", "hurry": "make haste", "run": "fly",
  "think": "trow", "know": "wot", "guess": "surmise",
  "said": "quoth", "says": "saith", "talk": "discourse",
  "speak": "speak", "tell": "impart", "ask": "beseech",
  "want": "desire", "wants": "desireth", "need": "have need of",
  "like": "fancy", "love": "love", "hate": "abhor",
  "happy": "merry", "glad": "right glad", "sad": "melancholy",
  "angry": "wroth", "mad": "wroth", "afraid": "afeard",
  "scared": "afeard", "worried": "full of care", "tired": "aweary",
  "sick": "distempered", "hungry": "sharp-set", "drunk": "in his cups",
  "sleep": "slumber", "dead": "gone to dust", "die": "shuffle off this mortal coil",
  "died": "shuffled off this mortal coil", "kill": "dispatch",
  "eat": "feast upon", "drink": "quaff", "food": "victuals",
  "clothes": "raiment", "shoes": "buskins", "house": "dwelling",
  "school": "house of learning", "work": "labour",
  "job": "office", "boss": "liege lord", "teacher": "schoolmaster",
  "student": "scholar", "party": "revels", "fun": "merriment",
  "joke": "jest", "funny": "full of jest", "song": "ditty",
  "music": "sweet airs", "dance": "measure", "game": "sport",
  "problem": "vexation", "trouble": "woe", "mistake": "folly",
  "lie": "falsehood", "liar": "false knave", "truth": "sooth",
  "secret": "counsel", "news": "tidings", "story": "tale",
  "letter": "missive", "word": "word", "promise": "troth",
  "kiss": "buss", "hug": "embrace", "fight": "quarrel",
  "argue": "wrangle", "insult": "flout", "steal": "filch",
  "money": "coin", "rich": "wealthy as Croesus", "poor": "penniless",
  "expensive": "dear-bought", "cheap": "of small worth",
  "big": "great", "huge": "prodigious", "small": "little",
  "tiny": "a mote", "old": "ancient", "young": "youthful",
  "new": "newly-minted", "good": "good", "bad": "ill",
  "terrible": "most vile", "horrible": "monstrous", "evil": "foul",
  "wonderful": "wondrous", "perfect": "without blemish",
  "okay": "well enough", "ok": "well enough", "fine": "passing fair",
  "sure": "assuredly", "obviously": "as plain as day",
  "honestly": "in sooth", "seriously": "in sober earnest",
  "literally": "in very deed", "basically": "in plain terms",
  "whatever": "as thou wilt", "anyway": "howsoe'er",
  "because": "for that", "though": "albeit", "although": "albeit",
  "if": "an if", "until": "till", "while": "whilst",
  "why": "wherefore", "where": "whither", "nobody": "no wight",
  "everyone": "all the world", "everybody": "all the world",
  "somebody": "some wight", "someone": "some wight",
};

// ---------- Grammar: thou-form auxiliaries (after "thou") ----------
export const THOU_AUX = {
  "are": "art", "were": "wert", "will": "wilt", "would": "wouldst",
  "shall": "shalt", "should": "shouldst", "have": "hast", "had": "hadst",
  "do": "dost", "did": "didst", "can": "canst", "could": "couldst",
  "may": "mayst", "might": "mightst", "must": "must", "were not": "wert not",
};

// verbs safe to inflect with -est after thou
export const THOU_VERBS = {
  "know": "knowest", "speak": "speakest", "love": "lovest", "think": "thinkest",
  "come": "comest", "go": "goest", "say": "sayest", "see": "seest",
  "hear": "hearest", "want": "wantest", "make": "makest", "take": "takest",
  "give": "givest", "tell": "tellest", "look": "lookest", "need": "needest",
  "like": "likest", "feel": "feelest", "call": "callest", "find": "findest",
  "bring": "bringest", "seem": "seemest", "live": "livest", "stand": "standest",
  "sit": "sittest", "walk": "walkest", "talk": "talkest", "eat": "eatest",
  "drink": "drinkest", "sleep": "sleepest", "read": "readest", "write": "writest",
  "play": "playest", "work": "workest", "run": "runnest", "stay": "stayest",
  "wish": "wishest", "hope": "hopest", "fear": "fearest", "hold": "holdest",
};

// third-person -s verbs -> -eth forms
export const ETH_VERBS = {
  "has": "hath", "does": "doth", "says": "saith", "comes": "cometh",
  "goes": "goeth", "knows": "knoweth", "makes": "maketh", "gives": "giveth",
  "takes": "taketh", "tells": "telleth", "thinks": "thinketh", "loves": "loveth",
  "speaks": "speaketh", "sees": "seeth", "hears": "heareth", "wants": "wanteth",
  "needs": "needeth", "looks": "looketh", "calls": "calleth", "finds": "findeth",
  "brings": "bringeth", "seems": "seemeth", "lives": "liveth", "stands": "standeth",
  "sits": "sitteth", "walks": "walketh", "talks": "talketh", "eats": "eateth",
  "drinks": "drinketh", "sleeps": "sleepeth", "reads": "readeth", "writes": "writeth",
  "plays": "playeth", "works": "worketh", "runs": "runneth", "stays": "stayeth",
  "wishes": "wisheth", "hopes": "hopeth", "fears": "feareth", "holds": "holdeth",
  "feels": "feeleth", "likes": "liketh",
};

// ---------- Poetic contractions ----------
export const CONTRACTIONS_M2S = [
  ["it is", "'tis"], ["it's", "'tis"], ["it was", "'twas"],
  ["it will", "'twill"], ["it'll", "'twill"], ["it were", "'twere"],
  ["over", "o'er"], ["even", "e'en"],
];

// ---------- Flourishes (openers keyed to sentence mood) ----------
export const FLOURISH = {
  exclaim: ["Zounds!", "'Sblood!", "Odds bodkins!", "By heaven!", "O wonder!", "What ho!"],
  question: ["Pray tell,", "I beseech thee,", "How now,", "Say, sirrah,"],
  negative: ["Alack,", "Alas,", "Fie upon it!", "O woeful day!", "Out upon it!"],
  neutral: ["Marry,", "In faith,", "By my troth,", "Forsooth,", "Hark ye,", "Look you,", "I' faith,"],
  closer: ["— and there an end.", "— so say we all.", "— mark it well.", "— thereby hangs a tale."],
};

// ---------- Insults: real lines + a construction kit from the plays ----------
export const INSULT_QUOTES = [
  { text: "Thou art a boil, a plague-sore, an embossed carbuncle in my corrupted blood.", source: "King Lear, Act 2, Scene 4" },
  { text: "Away, you scullion! You rampallian! You fustilarian! I'll tickle your catastrophe.", source: "Henry IV Part 2, Act 2, Scene 1" },
  { text: "Thou clay-brained guts, thou knotty-pated fool, thou whoreson obscene greasy tallow-catch!", source: "Henry IV Part 1, Act 2, Scene 4" },
  { text: "More of your conversation would infect my brain.", source: "Coriolanus, Act 2, Scene 1" },
  { text: "Peace, ye fat guts!", source: "Henry IV Part 1, Act 2, Scene 2" },
  { text: "Thou elvish-marked, abortive, rooting hog!", source: "Richard III, Act 1, Scene 3" },
  { text: "Out of my sight! Thou dost infect mine eyes.", source: "Richard III, Act 1, Scene 2" },
  { text: "Thou sodden-witted lord! Thou hast no more brain than I have in mine elbows.", source: "Troilus and Cressida, Act 2, Scene 1" },
  { text: "I do desire we may be better strangers.", source: "As You Like It, Act 3, Scene 2" },
  { text: "Away, you three-inch fool!", source: "The Taming of the Shrew, Act 4, Scene 1" },
  { text: "Thine face is not worth sunburning.", source: "Henry V, Act 5, Scene 2" },
  { text: "You Banbury cheese!", source: "The Merry Wives of Windsor, Act 1, Scene 1" },
  { text: "Thou cream-faced loon! Where got'st thou that goose look?", source: "Macbeth, Act 5, Scene 3" },
  { text: "Go, prick thy face, and over-red thy fear, thou lily-livered boy.", source: "Macbeth, Act 5, Scene 3" },
  { text: "His wit's as thick as a Tewkesbury mustard.", source: "Henry IV Part 2, Act 2, Scene 4" },
  { text: "Methink'st thou art a general offence, and every man should beat thee.", source: "All's Well That Ends Well, Act 2, Scene 3" },
  { text: "There's no more faith in thee than in a stewed prune.", source: "Henry IV Part 1, Act 3, Scene 3" },
  { text: "You starveling, you eel-skin, you dried neat's-tongue, you bull's-pizzle, you stock-fish!", source: "Henry IV Part 1, Act 2, Scene 4" },
  { text: "Thou art as loathsome as a toad.", source: "Troilus and Cressida, Act 2, Scene 1" },
  { text: "I scorn you, scurvy companion.", source: "Henry IV Part 2, Act 2, Scene 4" },
];

// Insult kit: every fragment appears in Shakespeare's works
export const INSULT_KIT = {
  adj1: ["artless","bawdy","beslubbering","bootless","churlish","cockered","clouted","craven","currish","dankish","dissembling","droning","errant","fawning","fobbing","froward","frothy","gleeking","goatish","gorbellied","impertinent","infectious","jarring","loggerheaded","lumpish","mammering","mangled","mewling","paunchy","pribbling","puking","puny","qualling","rank","reeky","roguish","ruttish","saucy","spleeny","spongy","surly","tottering","unmuzzled","vain","venomed","villainous","warped","wayward","weedy","yeasty"],
  adj2: ["base-court","bat-fowling","beef-witted","beetle-headed","boil-brained","clapper-clawed","clay-brained","common-kissing","crook-pated","dismal-dreaming","dizzy-eyed","doghearted","dread-bolted","earth-vexing","elf-skinned","fat-kidneyed","fen-sucked","flap-mouthed","fly-bitten","folly-fallen","fool-born","full-gorged","guts-griping","half-faced","hasty-witted","hedge-born","hell-hated","idle-headed","ill-breeding","ill-nurtured","knotty-pated","milk-livered","motley-minded","onion-eyed","plume-plucked","pottle-deep","pox-marked","reeling-ripe","rough-hewn","rude-growing","rump-fed","shard-borne","sheep-biting","spur-galled","swag-bellied","tardy-gaited","tickle-brained","toad-spotted","unchin-snouted","weather-bitten"],
  noun: ["apple-john","baggage","barnacle","bladder","boar-pig","bugbear","bum-bailey","canker-blossom","clack-dish","clotpole","coxcomb","codpiece","death-token","dewberry","flap-dragon","flax-wench","flirt-gill","foot-licker","fustilarian","giglet","gudgeon","haggard","harpy","hedge-pig","horn-beast","hugger-mugger","joithead","lewdster","lout","maggot-pie","malt-worm","mammet","measle","minnow","miscreant","moldwarp","mumble-news","nut-hook","pigeon-egg","pignut","puttock","pumpion","ratsbane","scut","skainsmate","vassal","varlet","whey-face","wagtail"],
};

// ---------- Famous quotes by theme (for the "Bard's Wisdom" panel) ----------
export const QUOTES = [
  { theme: "love", text: "Shall I compare thee to a summer's day? Thou art more lovely and more temperate.", source: "Sonnet 18" },
  { theme: "love", text: "The course of true love never did run smooth.", source: "A Midsummer Night's Dream, Act 1, Scene 1" },
  { theme: "love", text: "Love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind.", source: "A Midsummer Night's Dream, Act 1, Scene 1" },
  { theme: "doubt", text: "To be, or not to be, that is the question.", source: "Hamlet, Act 3, Scene 1" },
  { theme: "doubt", text: "Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt.", source: "Measure for Measure, Act 1, Scene 4" },
  { theme: "ambition", text: "I have no spur to prick the sides of my intent, but only vaulting ambition, which o'erleaps itself.", source: "Macbeth, Act 1, Scene 7" },
  { theme: "courage", text: "Screw your courage to the sticking-place, and we'll not fail.", source: "Macbeth, Act 1, Scene 7" },
  { theme: "courage", text: "Once more unto the breach, dear friends, once more.", source: "Henry V, Act 3, Scene 1" },
  { theme: "wisdom", text: "The fool doth think he is wise, but the wise man knows himself to be a fool.", source: "As You Like It, Act 5, Scene 1" },
  { theme: "wisdom", text: "Brevity is the soul of wit.", source: "Hamlet, Act 2, Scene 2" },
  { theme: "fate", text: "All the world's a stage, and all the men and women merely players.", source: "As You Like It, Act 2, Scene 7" },
  { theme: "fate", text: "It is not in the stars to hold our destiny but in ourselves.", source: "Julius Caesar (adapted), Act 1, Scene 2" },
  { theme: "time", text: "We are such stuff as dreams are made on, and our little life is rounded with a sleep.", source: "The Tempest, Act 4, Scene 1" },
  { theme: "grief", text: "Give sorrow words: the grief that does not speak whispers the o'er-fraught heart and bids it break.", source: "Macbeth, Act 4, Scene 3" },
  { theme: "mischief", text: "Lord, what fools these mortals be!", source: "A Midsummer Night's Dream, Act 3, Scene 2" },
  { theme: "mischief", text: "Though she be but little, she is fierce.", source: "A Midsummer Night's Dream, Act 3, Scene 2" },
];

// ---------- Shakespearean -> Modern glossary (word: [modern, note]) ----------
export const GLOSS_S2M = {
  "thou": ["you", "subject form: 'thou art' = 'you are'"],
  "thee": ["you", "object form: 'I see thee' = 'I see you'"],
  "thy": ["your", "before a consonant: 'thy sword'"],
  "thine": ["your / yours", "before a vowel ('thine eyes') or standing alone"],
  "thyself": ["yourself", ""],
  "ye": ["you (plural)", "addressing more than one person"],
  "art": ["are", "used with 'thou'"],
  "wert": ["were", "used with 'thou'"],
  "wilt": ["will", "used with 'thou'"],
  "shalt": ["shall / will", "used with 'thou'"],
  "hast": ["have", "used with 'thou'"],
  "hath": ["has", ""],
  "hadst": ["had", "used with 'thou'"],
  "dost": ["do", "used with 'thou'"],
  "doth": ["does", ""],
  "didst": ["did", "used with 'thou'"],
  "canst": ["can", "used with 'thou'"],
  "couldst": ["could", "used with 'thou'"],
  "wouldst": ["would", "used with 'thou'"],
  "shouldst": ["should", "used with 'thou'"],
  "mayst": ["may", "used with 'thou'"],
  "mightst": ["might", "used with 'thou'"],
  "anon": ["soon / right away", "'I come anon' = 'I'm coming'"],
  "aught": ["anything", ""],
  "naught": ["nothing", ""],
  "aye": ["yes", ""],
  "nay": ["no", ""],
  "ere": ["before", "'ere long' = 'before long'"],
  "oft": ["often", ""],
  "e'er": ["ever", "poetic contraction"],
  "ne'er": ["never", "poetic contraction"],
  "o'er": ["over", "poetic contraction"],
  "e'en": ["even / evening", "poetic contraction"],
  "'tis": ["it is", ""],
  "'twas": ["it was", ""],
  "'twill": ["it will", ""],
  "'twere": ["it were / it would be", ""],
  "betwixt": ["between", ""],
  "hither": ["here / to here", "'come hither' = 'come here'"],
  "thither": ["there / to there", ""],
  "whither": ["where / to where", "'whither goest thou?' = 'where are you going?'"],
  "whence": ["from where", ""],
  "hence": ["from here / away", "also 'therefore'"],
  "thence": ["from there", ""],
  "yonder": ["over there", ""],
  "hark": ["listen", ""],
  "prithee": ["please", "short for 'I pray thee'"],
  "beseech": ["beg", "'I beseech you' = 'I beg you'"],
  "perchance": ["maybe / by chance", ""],
  "haply": ["perhaps / by luck", ""],
  "mayhap": ["perhaps", ""],
  "verily": ["truly", ""],
  "forsooth": ["truly / indeed", "often sarcastic"],
  "sooth": ["truth", "'in sooth' = 'truly'"],
  "certes": ["certainly", ""],
  "marry": ["indeed / well", "a mild oath, from 'by the Virgin Mary'"],
  "zounds": ["an oath of surprise", "from 'by God's wounds'"],
  "'sblood": ["an oath of anger", "from 'by God's blood'"],
  "fie": ["shame! / nonsense!", "exclamation of disgust"],
  "alack": ["alas / oh no", ""],
  "alas": ["oh no / sadly", ""],
  "avaunt": ["go away!", ""],
  "morrow": ["morning", "'good morrow' = 'good morning'"],
  "yesternight": ["last night", ""],
  "fortnight": ["two weeks", ""],
  "sennight": ["one week", ""],
  "methinks": ["I think / it seems to me", ""],
  "methought": ["I thought / it seemed to me", ""],
  "quoth": ["said", "'quoth he' = 'he said'"],
  "saith": ["says", ""],
  "wot": ["know", "'I wot not' = 'I don't know'"],
  "trow": ["believe / suppose", ""],
  "ween": ["think / imagine", ""],
  "wherefore": ["why", "'wherefore art thou Romeo?' = 'WHY are you Romeo?' — not 'where'!"],
  "wench": ["young woman", "not originally an insult"],
  "sirrah": ["'hey, you'", "address to a social inferior; often contemptuous"],
  "coz": ["cousin / friend", "used for almost any relative or close friend"],
  "knave": ["rascal / scoundrel", ""],
  "varlet": ["rogue / rascal", ""],
  "villain": ["scoundrel", "originally 'low-born person'"],
  "wight": ["person / creature", ""],
  "fain": ["gladly", "'I would fain go' = 'I would gladly go'"],
  "bootless": ["useless / pointless", "nothing to do with boots"],
  "cozen": ["cheat / deceive", ""],
  "fardel": ["burden / bundle", "'who would fardels bear?' — Hamlet"],
  "mark": ["pay attention to", "'mark me' = 'listen closely'"],
  "meet": ["proper / fitting", "'it is meet' = 'it is appropriate'"],
  "perforce": ["necessarily / by force", ""],
  "presently": ["immediately", "NOT 'in a while' — it meant 'right now'"],
  "straight": ["immediately", "'I'll do it straight'"],
  "rank": ["foul / rotten", "'something is rotten' territory"],
  "sans": ["without", "borrowed from French"],
  "saucy": ["insolent / rude", "much stronger than today"],
  "visage": ["face", ""],
  "countenance": ["face / expression", ""],
  "wax": ["grow / become", "'wax angry' = 'become angry'"],
  "weal": ["wellbeing / prosperity", "'the common weal'"],
  "woe": ["sorrow / misery", ""],
  "withal": ["with it / besides", ""],
  "howsoe'er": ["however", ""],
  "albeit": ["although", ""],
  "whilst": ["while", ""],
  "an": ["if", "'an it please you' = 'if it pleases you'"],
  "troth": ["faith / loyalty", "'by my troth' = 'I swear'"],
  "gramercy": ["many thanks", "from French 'grand merci'"],
  "grammercy": ["many thanks", "from French 'grand merci'"],
  "adieu": ["goodbye", "French: 'to God'"],
  "apace": ["quickly", ""],
  "hie": ["hurry", "'hie thee home' = 'hurry home'"],
  "tarry": ["wait / linger", ""],
  "abide": ["stay / endure", ""],
  "attend": ["listen to / wait upon", ""],
  "peradventure": ["perhaps", ""],
  "beshrew": ["curse", "'beshrew me' = 'curse me' (mildly)"],
  "bade": ["asked / commanded", "past tense of 'bid'"],
  "durst": ["dared", ""],
  "spake": ["spoke", ""],
  "clept": ["called / named", ""],
  "hight": ["called / named", ""],
  "erstwhile": ["former / formerly", ""],
  "whoreson": ["scoundrel (crude)", "literally 'son of a whore' — a crude insult"],
  "cuckold": ["a man whose wife is unfaithful", "the great Elizabethan fear"],
  "dotage": ["senility / foolish love", ""],
  "choler": ["anger", "from the four humours"],
  "wroth": ["angry", ""],
  "afeard": ["afraid", ""],
  "aweary": ["weary / tired", ""],
  "anent": ["about / concerning", ""],
  "orisons": ["prayers", "'nymph, in thy orisons be all my sins remembered'"],
  "shrift": ["confession", "'short shrift' comes from this"],
  "quietus": ["release / settlement", "in Hamlet, a euphemism for death"],
  "palter": ["equivocate / deceive", ""],
  "moiety": ["portion / half", ""],
  "nonce": ["present occasion", "'for the nonce' = 'for now'"],
  "vouchsafe": ["grant / deign to give", ""],
  "beteem": ["allow / grant", ""],
  "gainsay": ["deny / contradict", ""],
  "lief": ["gladly", "'I had as lief' = 'I would just as soon'"],
  "loth": ["reluctant", "modern 'loath'"],
  "privy": ["secretly aware", "'privy to' = 'in on the secret'"],
  "several": ["separate / various", "'our several ways'"],
  "still": ["always / constantly", "'still weeping' = 'always weeping'"],
  "want": ["lack", "'he wants wit' = 'he lacks intelligence'"],
  "owe": ["own / possess", "'the powers that he owes'"],
  "passing": ["extremely / surpassingly", "'passing strange' = 'very strange'"],
  "brave": ["fine / splendid", "'O brave new world' = 'O splendid new world'"],
  "fond": ["foolish", "'fond old man'"],
  "jealous": ["suspicious", "broader than romantic jealousy"],
  "nice": ["precise / fussy / trivial", "almost never meant 'kind'"],
  "sad": ["serious / grave", "often meant 'solemn', not 'unhappy'"],
  "silly": ["innocent / helpless", "'silly sheep' = 'defenseless sheep'"],
  "quaint": ["clever / skillfully made", ""],
  "puissant": ["powerful", ""],
  "arrant": ["utter / complete", "'arrant knave' = 'total scoundrel'"],
  "errant": ["wandering / utter", ""],
  "peevish": ["silly / obstinate", ""],
  "froward": ["stubborn / contrary", ""],
  "lusty": ["vigorous / lively", "not necessarily lustful"],
  "wanton": ["playful / unrestrained", "could be innocent or not"],
  "paramour": ["lover", ""],
  "leman": ["sweetheart / lover", ""],
  "dalliance": ["idle flirtation / wasting time", ""],
  "revels": ["festivities / partying", ""],
  "masque": ["masked entertainment", "a courtly party performance"],
  "victuals": ["food", "pronounced 'vittles'"],
  "sack": ["Spanish white wine", "Falstaff's favourite drink"],
  "posset": ["hot milk drink with wine", "an Elizabethan nightcap"],
  "raiment": ["clothing", ""],
  "doublet": ["a man's fitted jacket", ""],
  "kirtle": ["a woman's gown or skirt", ""],
  "buskins": ["boots", ""],
  "ducats": ["gold coins", "Venetian currency"],
  "groat": ["a small coin", "fourpence"],
  "sixpence": ["a small coin", "six pennies"],
  "physic": ["medicine", ""],
  "plague": ["curse / disease", "'a plague on both your houses!'"],
  "pox": ["disease (curse word)", "'a pox on it!'"],
  "carbuncle": ["boil / red gem", "in insults: an inflamed sore"],
  "canker": ["disease / corruption / rose worm", ""],
  "gall": ["bitterness / to irritate", ""],
  "spleen": ["temper / impulse", "thought to be the seat of passions"],
  "humour": ["mood / temperament", "from the four bodily humours"],
  "welkin": ["sky / heavens", ""],
  "firmament": ["sky", "'this brave o'erhanging firmament'"],
  "orb": ["sphere / world / star", ""],
  "bark": ["ship / small boat", ""],
  "bourn": ["boundary / region", "'from whose bourn no traveller returns'"],
  "clime": ["climate / region", ""],
  "mead": ["meadow", "also: honey wine"],
  "bower": ["shady retreat / bedroom", ""],
  "swain": ["young country man / suitor", ""],
  "yon": ["that (over there)", "'yon window'"],
  "attorney": ["agent / representative", "broader than lawyer"],
  "engine": ["device / plot / instrument", "any clever contraption"],
  "practise": ["scheme / plot", "often sinister"],
  "policy": ["cunning / statecraft", "often devious"],
  "commend": ["entrust / send greetings", "'commend me to them'"],
  "resolve": ["answer / decide / dissolve", ""],
  "discourse": ["conversation / talk", ""],
  "conference": ["conversation", ""],
  "intelligence": ["news / information / spying", ""],
  "advertisement": ["advice / warning", "nothing to do with ads"],
  "closet": ["private room / study", "not a wardrobe"],
  "habit": ["clothing / costume", "'in the habit of a friar'"],
  "suit": ["petition / courtship", "'press my suit'"],
  "favour": ["face / appearance / token", "'well-favoured' = 'good-looking'"],
  "complexion": ["temperament / appearance", ""],
  "colour": ["pretext / excuse", "'under colour of'"],
  "shadow": ["ghost / image / actor", ""],
  "shade": ["ghost / spirit", ""],
  "spirit": ["ghost / courage / mind", ""],
  "bodements": ["omens", ""],
  "augury": ["omen-reading / prophecy", ""],
  "soothsayer": ["fortune-teller", "'beware the ides of March'"],
  "ides": ["the 15th (of March, May, July, Oct)", "or 13th of other months"],
  "exeunt": ["they exit", "stage direction, Latin plural of 'exit'"],
  "alarum": ["call to arms", "stage direction for battle noise"],
  "flourish": ["trumpet fanfare", "stage direction for royalty entering"],
};

// ---------- Shakespearean -> Modern phrase replacements ----------
export const PHRASES_S2M = [
  ["fare thee well", "goodbye"],
  ["fare you well", "goodbye"],
  ["good morrow", "good morning"],
  ["good even", "good evening"],
  ["good e'en", "good evening"],
  ["how now", "hey — what's going on?"],
  ["what ho", "hey there!"],
  ["by my troth", "I swear"],
  ["in sooth", "truly"],
  ["in faith", "honestly"],
  ["i' faith", "honestly"],
  ["by heaven", "oh my god"],
  ["get thee gone", "go away"],
  ["get thee hence", "go away"],
  ["come hither", "come here"],
  ["hie thee", "hurry"],
  ["hold thy tongue", "be quiet"],
  ["hold your tongue", "be quiet"],
  ["i cry thee mercy", "I beg your pardon"],
  ["i pray thee", "please"],
  ["i pray you", "please"],
  ["pray tell", "please tell me"],
  ["would that", "I wish that"],
  ["it likes me not", "I don't like it"],
  ["how dost thou", "how are you"],
  ["how dost thou fare", "how are you"],
  ["how fares", "how is"],
  ["what say you", "what do you think"],
  ["what says thou", "what do you say"],
  ["soft you now", "hold on a moment"],
  ["but soft", "wait a moment"],
  ["lend me your ears", "listen up"],
  ["all the world", "everyone"],
  ["well met", "nice to see you"],
  ["ill met", "unpleasant to run into you"],
  ["anon, anon", "coming, coming!"],
  ["much ado", "a lot of fuss"],
  ["the more the pity", "that's too bad"],
  ["a plague on", "curse"],
  ["a pox on", "curse"],
  ["out upon", "shame on"],
  ["fie upon", "shame on"],
  ["would i were", "I wish I were"],
  ["thereby hangs a tale", "there's a story behind that"],
];

// ---------- Famous passages, detectable in student mode ----------
export const FAMOUS_LINES = [
  { match: "to be or not to be", source: "Hamlet, Act 3, Scene 1", gist: "Hamlet weighs whether living or dying is the braver choice." },
  { match: "wherefore art thou romeo", source: "Romeo and Juliet, Act 2, Scene 2", gist: "Juliet asks WHY Romeo must be a Montague — not where he is." },
  { match: "all the world's a stage", source: "As You Like It, Act 2, Scene 7", gist: "Jaques compares life to a play in seven acts." },
  { match: "et tu brute", source: "Julius Caesar, Act 3, Scene 1", gist: "Caesar's dying shock that his friend Brutus joined the conspirators." },
  { match: "double double toil and trouble", source: "Macbeth, Act 4, Scene 1", gist: "The three witches brew a spell." },
  { match: "is this a dagger which i see before me", source: "Macbeth, Act 2, Scene 1", gist: "Macbeth hallucinates a dagger before murdering King Duncan." },
  { match: "the quality of mercy is not strained", source: "The Merchant of Venice, Act 4, Scene 1", gist: "Portia argues that mercy blesses both giver and receiver." },
  { match: "if you prick us do we not bleed", source: "The Merchant of Venice, Act 3, Scene 1", gist: "Shylock's plea for common humanity." },
  { match: "now is the winter of our discontent", source: "Richard III, Act 1, Scene 1", gist: "Richard opens the play plotting his rise to power." },
  { match: "a horse a horse my kingdom for a horse", source: "Richard III, Act 5, Scene 4", gist: "Richard, unhorsed in battle, would trade everything to escape." },
  { match: "friends romans countrymen", source: "Julius Caesar, Act 3, Scene 2", gist: "Antony's funeral speech turns the crowd against the conspirators." },
  { match: "once more unto the breach", source: "Henry V, Act 3, Scene 1", gist: "Henry rallies his soldiers at the siege of Harfleur." },
  { match: "we few we happy few we band of brothers", source: "Henry V, Act 4, Scene 3", gist: "Henry's St. Crispin's Day speech before Agincourt." },
  { match: "the lady doth protest too much", source: "Hamlet, Act 3, Scene 2", gist: "Gertrude finds the Player Queen's vows suspiciously extravagant." },
  { match: "something is rotten in the state of denmark", source: "Hamlet, Act 1, Scene 4", gist: "Marcellus senses corruption at the Danish court." },
  { match: "shall i compare thee to a summer's day", source: "Sonnet 18", gist: "The poet promises immortality through verse." },
  { match: "beware the ides of march", source: "Julius Caesar, Act 1, Scene 2", gist: "A soothsayer warns Caesar of March 15 — the day he'll be assassinated." },
  { match: "o brave new world", source: "The Tempest, Act 5, Scene 1", gist: "Miranda marvels at seeing other humans for the first time." },
  { match: "lord what fools these mortals be", source: "A Midsummer Night's Dream, Act 3, Scene 2", gist: "Puck laughs at the tangled human lovers." },
  { match: "parting is such sweet sorrow", source: "Romeo and Juliet, Act 2, Scene 2", gist: "Juliet's goodbye — sad to part, sweet because they'll meet again." },
];

// ---------- Stage directions & character names for Script Mode ----------
export const STAGE_DIRECTIONS = [
  "Enter, with a flourish of trumpets",
  "Aside",
  "They fight",
  "Exit, pursued by a bear",
  "Alarum within",
  "Thunder and lightning",
  "Enter, reading a letter",
  "Dies",
  "Exeunt omnes",
  "Music plays",
];

export const CHARACTER_SUGGESTIONS = [
  "DUKE ORSINO", "MISTRESS QUICKLY", "SIR TOBY BELCH", "PUCK", "FIRST WITCH",
  "A GRAVEDIGGER", "THE FOOL", "LADY MACBETH", "FALSTAFF", "OPHELIA",
  "A MESSENGER", "SECOND MURDERER", "THE NURSE", "PROSPERO", "BOTTOM THE WEAVER",
];

export const LOADING_LINES = [
  "Dipping the quill…",
  "Consulting the First Folio…",
  "Waking the ghost of Hamlet's father…",
  "Bribing the printers of the Globe…",
  "Untangling iambic pentameter…",
];
