// Bardify Generational Translator — era lexicon
// Every entry: { a: anchor concept id, o: original/neutral/archaic forms it may match,
//                genalpha/genz/millennial/genx/boomer/jazz: replacement variants for that era }
// All entries are school-safe by default (tier 0 = fine for any classroom,
// tier 1 = mildly salty, only shown when the classroom filter is relaxed).
// Slang decays fast — this file is meant to be updated; see README "Keeping slang fresh".

export const ERAS = [
  { id: "genalpha", name: "Gen Alpha", years: "~2010s–now", tagline: "The brainrot era — short-form video natives",
    style: { lowercase: true, intensifiers: ["fr", "no cap", "fr fr", "ong"], openers: ["yo", "bro"], closers: ["on my soul", "deadass"] , emojis: ["💀", "🗣️", "🔥"] } },
  { id: "genz", name: "Gen Z", years: "~1997–2012", tagline: "The extremely-online generation",
    style: { lowercase: true, intensifiers: ["fr", "no cap", "lowkey", "highkey", "ong"], openers: ["bestie", "bruh", "bro"], closers: ["and that's on period", "iykyk"], emojis: ["💀", "😭", "🔥", "✨"] } },
  { id: "millennial", name: "Millennial", years: "~1981–1996", tagline: "Avocado toast era, literally",
    style: { lowercase: false, intensifiers: ["literally", "actually", "honestly"], openers: ["okay so", "real talk"], closers: ["just sayin'", "no but for real"], emojis: ["😂", "💯", "🙌"] } },
  { id: "genx", name: "Generation X", years: "~1965–1980", tagline: "The whatever generation",
    style: { lowercase: false, intensifiers: ["totally", "seriously", "wicked"], openers: ["look", "so"], closers: ["whatever", "I'm just sayin'"], emojis: [] } },
  { id: "boomer", name: "Baby Boomer", years: "~1946–1964", tagline: "Far out, man",
    style: { lowercase: false, intensifiers: ["mighty", "real", "darn"], openers: ["say", "listen here", "boy"], closers: ["I tell ya", "that's the ticket"], emojis: [] } },
  { id: "jazz", name: "Roaring '20s", years: "~1920s", tagline: "The cat's pajamas, see",
    style: { lowercase: false, intensifiers: ["awfully", "swell", "mighty"], openers: ["say", "listen"], closers: ["see?", "and how!"], emojis: [] } },
];

// Maturity tiers on entries: 0 = school-safe, 1 = mild (shown only if filter relaxed)
export const LEXICON = [
  // --- greetings & address ---
  { a: "greet", o: ["hello", "hi", "hey", "hail", "well met", "good morrow", "good day", "good even", "what ho", "how now", "greetings", "god save you", "how do you do", "how do you fare"],
    genalpha: ["yo wsg", "yo", "what's good"], genz: ["wsg", "yooo", "hey bestie"], millennial: ["hey hey", "oh hi"], genx: ["hey", "yo"], boomer: ["well hello there", "howdy"], jazz: ["hiya", "well well"], tier: 0 },
  { a: "farewell", o: ["goodbye", "bye", "farewell", "adieu", "parting is such sweet sorrow", "i bid thee farewell", "good night", "i take my leave"],
    genalpha: ["i'm out", "peace", "gtg"], genz: ["i'm outie", "peace out", "aight imma head out"], millennial: ["catch you later", "gotta jet"], genx: ["later", "i'm outta here"], boomer: ["so long", "be seeing you"], jazz: ["23 skidoo", "cheerio"], tier: 0 },
  { a: "please", o: ["please", "prithee", "i pray thee", "i beseech thee", "i beg thee", "an't please you", "pray"],
    genalpha: ["plssss", "c'mon please"], genz: ["pls", "pleasee"], millennial: ["pretty please"], genx: ["come on, please"], boomer: ["if you would be so kind"], jazz: ["be a pal and"], tier: 0 },
  { a: "thanks", o: ["thank you", "thanks", "i thank thee", "gramercy", "many thanks", "i give thee thanks"],
    genalpha: ["tysm", "thanks king"], genz: ["ty", "ily thanks"], millennial: ["omg thanks"], genx: ["thanks, man"], boomer: ["much obliged", "thank you kindly"], jazz: ["thanks a bunch, see"], tier: 0 },
  { a: "sorry", o: ["sorry", "i am sorry", "forgive me", "pardon me", "i crave your pardon", "my apologies"],
    genalpha: ["my bad fr", "sorrrry"], genz: ["my b", "sorries"], millennial: ["sorry not sorry"], genx: ["yeah my bad"], boomer: ["beg your pardon"], jazz: ["pardon me, see"], tier: 0 },
  { a: "hey-you", o: ["sirrah", "you there", "sir", "madam", "my lord", "my lady", "milady", "lordship", "master", "mistress", "ho", "hold"],
    genalpha: ["bro", "bruh"], genz: ["bestie", "dawg", "fam"], millennial: ["dude", "buddy"], genx: ["man", "dude"], boomer: ["young fella", "pal"], jazz: ["ol' sport", "mack"], tier: 0 },
  // --- agreement / disagreement ---
  { a: "yes", o: ["yes", "yea", "ay", "indeed", "forsooth", "verily", "certainly", "most certainly", "it is so", "'tis true"],
    genalpha: ["bet", "ong yes"], genz: ["bet", "facts", "fr yes"], millennial: ["absolutely", "heck yes"], genx: ["yeah totally"], boomer: ["you betcha", "by golly yes"], jazz: ["yes siree", "you bet"], tier: 0 },
  { a: "no", o: ["no", "nay", "never", "not so", "by no means", "certainly not", "'tis not so"],
    genalpha: ["nahhh", "no shot"], genz: ["nah", "no way fr"], millennial: ["um no", "hard pass"], genx: ["no way"], boomer: ["heck no", "not on your life"], jazz: ["nuts to that", "no dice"], tier: 0 },
  { a: "maybe", o: ["maybe", "perhaps", "peradventure", "mayhap", "it may be", "perchance"],
    genalpha: ["idk maybe", "lowkey maybe"], genz: ["maybe idk", "prolly"], millennial: ["maybe???", "i mean maybe"], genx: ["eh maybe"], boomer: ["well, might be"], jazz: ["maybe so, maybe so"], tier: 0 },
  { a: "agree-strongly", o: ["amen", "well said", "thou speakest truth", "thou art right", "i agree", "truly", "sooth"],
    genalpha: ["ong", "spit facts"], genz: ["preach", "no bc real", "so real for that"], millennial: ["yes, this", "this is it"], genx: ["exactly", "right on"], boomer: ["hear hear", "attaboy"], jazz: ["attaboy", "now you're talking"], tier: 0 },
  { a: "disagree", o: ["i disagree", "thou art wrong", "not so", "i think not", "thou liest"],
    genalpha: ["nah u wrong", "not even"], genz: ["wrong, actually", "nah miss me with that"], millennial: ["i'm gonna go with no"], genx: ["as if", "yeah right"], boomer: ["now hold on there"], jazz: ["phooey", "applesauce"], tier: 0 },
  // --- evaluation ---
  { a: "good", o: ["good", "well", "fine", "excellent", "wonderful", "splendid", "worthy", "honorable", "fair", "brave", "gallant", "noble", "goodly"],
    genalpha: ["fire", "peak", "goated"], genz: ["fire", "lit", "slaps"], millennial: ["awesome", "epic"], genx: ["rad", "badass"], boomer: ["swell", "dandy"], jazz: ["swell", "the bee's knees", "the cat's pajamas"], tier: 0 },
  { a: "bad", o: ["bad", "ill", "poor", "wretched", "foul", "base", "vile", "unkind", "rotten", "sorry", "crummy"],
    genalpha: ["mid", "mid af", "down bad"], genz: ["mid", "trash", "l + ratio energy"], millennial: ["lame", "weak sauce"], genx: ["bogus", "weak"], boomer: ["lousy", "no good"], jazz: ["all wet", "rotten"], tier: 0 },
  { a: "very", o: ["very", "much", "greatly", "exceeding", "most", "sorely", "passing", "exceedingly"],
    genalpha: ["so so", "mad"], genz: ["mad", "hella", "v"], millennial: ["super", "so so"], genx: ["totally", "wicked"], boomer: ["mighty", "real"], jazz: ["awfully", "ever so"], tier: 0 },
  { a: "cool", o: ["cool", "impressive", "fine", "gallant", "admirable", "comely"],
    genalpha: ["aura", "sigma vibes", "so fire"], genz: ["drippy", "clean", "a vibe"], millennial: ["badass", "sick"], genx: ["gnarly", "cool as hell"], boomer: ["groovy", "nifty"], jazz: ["the cat's meow", "copacetic"], tier: 1, n: "cool" },
  { a: "beautiful", o: ["beautiful", "fair", "lovely", "beauteous", "comely", "fair-faced", "most fair"],
    genalpha: ["so fine fr", "gorgeous omg"], genz: ["gorgeous", "ate that look", "serving"], millennial: ["stunning", "gorge"], genx: ["a knockout", "foxy"], boomer: ["a looker", "a beauty"], jazz: ["the berries", "a real looker"], tier: 0 },
  { a: "ugly", o: ["ugly", "foul", "ill-favored", "unseemly", "lumpish", "unsightly"],
    genalpha: ["cooked-looking", "built different (in a bad way)"], genz: ["cooked", "no bc the facecard declined"], millennial: ["rough-looking"], genx: ["plug-ugly"], boomer: ["homely"], jazz: ["a face for radio"], tier: 0 },
  { a: "smart", o: ["wise", "clever", "learned", "cunning", "sage", "witty", "wit", "discerning"],
    genalpha: ["big brain", "megamind"], genz: ["galaxy brain", "big brain energy"], millennial: ["genius move"], genx: ["sharp"], boomer: ["bright as a button"], jazz: ["keen", "a clever cookie"], tier: 0 },
  { a: "foolish", o: ["fool", "foolish", "dull", "clown", "dolt", "ass", "knave", "blockhead", "witless", "idiot", "simple", "silly"],
    genalpha: ["zero braincells", "no thoughts head empty", "npc behavior"], genz: ["clowned", "fumbled", "no thoughts"], millennial: ["a total derp"], genx: ["a dweeb", "a dork"], boomer: ["a knucklehead", "a numbskull"], jazz: ["a palooka", "a dumb dora"], tier: 0 },
  { a: "crazy", o: ["mad", "madness", "lunatic", "besotted", "unhinged", "frenzied", "raving"],
    genalpha: ["unhinged fr", "off the rails"], genz: ["feral", "unhinged"], millennial: ["bonkers"], genx: ["nuts", "bananas"], boomer: ["cuckoo", "off their rocker"], jazz: ["goofy", "off their nut"], tier: 0 },
  { a: "true", o: ["true", "truth", "truly", "in truth", "by my troth", "upon my word", "i swear", "honest", "honestly"],
    genalpha: ["no cap", "ong"], genz: ["no cap", "fr fr", "deadass"], millennial: ["legit", "for real though"], genx: ["no lie", "for real"], boomer: ["honest to goodness", "scout's honor"], jazz: ["i'm on the level, see"], tier: 0 },
  { a: "lie", o: ["lie", "liar", "false", "falsehood", "deceit", "deceive", "fib", "thou liest", "lying"],
    genalpha: ["cap", "capping"], genz: ["cap", "that's cap"], millennial: ["fugazi", "a tall tale"], genx: ["a crock"], boomer: ["baloney", "hogwash"], jazz: ["applesauce", "a frame"], tier: 0 },
  // --- feelings ---
  { a: "love", o: ["love", "adore", "dote on", "am fond of", "my heart", "beloved", "dear", "sweetheart", "my love", "i love thee"],
    genalpha: ["down bad for", "obsessed fr"], genz: ["down bad", "obsessed", "simp over"], millennial: ["smitten", "swooning"], genx: ["sweet on", "crushing on"], boomer: ["smitten", "sweet on"], jazz: ["sweet on", "carrying a torch"], tier: 0 },
  { a: "hate", o: ["hate", "loathe", "detest", "abhor", "despise", "cannot abide", "curse"],
    genalpha: ["beef with", "can't stand fr"], genz: ["despise fr", "got beef"], millennial: ["cannot even with"], genx: ["hate their guts"], boomer: ["can't stomach"], jazz: ["got a grudge, see"], tier: 0 },
  { a: "sad", o: ["sad", "sorrow", "grief", "woe", "melancholy", "weep", "mourn", "lament", "heavy heart", "despair", "alas"],
    genalpha: ["so cooked", "down bad rn"], genz: ["in my feels", "sobbing fr"], millennial: ["in my feelings", "big sad"], genx: ["bummed out"], boomer: ["down in the dumps"], jazz: ["in the dumps, see"], tier: 0 },
  { a: "happy", o: ["happy", "glad", "joy", "joyful", "merry", "rejoiced", "delighted", "pleased", "content", "cheerful"],
    genalpha: ["so hype", "living rn"], genz: ["thriving", "vibing fr"], millennial: ["stoked", "psyched"], genx: ["psyched"], boomer: ["tickled pink", "happy as a clam"], jazz: ["tickled", "on cloud nine"], tier: 0 },
  { a: "angry", o: ["angry", "wrath", "fury", "furious", "enraged", "vexed", "choleric", "outraged"],
    genalpha: ["big mad", "crashing out"], genz: ["big mad", "heated fr"], millennial: ["fuming"], genx: ["ticked off", "steamed"], boomer: ["fit to be tied", "hopping mad"], jazz: ["hot under the collar"], tier: 0 },
  { a: "scared", o: ["afraid", "scared", "fear", "frightened", "terrified", "dread", "tremble", "quaking"],
    genalpha: ["spooked fr", "scaredy"], genz: ["shook", "lowkey terrified"], millennial: ["freaking out"], genx: ["spooked"], boomer: ["scared stiff", "yellow"], jazz: ["got the jitters"], tier: 0 },
  { a: "tired", o: ["tired", "weary", "exhausted", "fatigued", "spent", "worn"],
    genalpha: ["so sleepy fr", "cooked rn"], genz: ["dead tired", "exhausted fr"], millennial: ["so tired, so adult"], genx: ["beat", "wiped out"], boomer: ["plumb tuckered out"], jazz: ["all in, see"], tier: 0 },
  { a: "excited", o: ["excited", "thrilled", "eager", "keen", "agog"],
    genalpha: ["so hype", "hype train"], genz: ["hyped", "so ready fr"], millennial: ["stoked", "amped"], genx: ["pumped", "amped up"], boomer: ["eager beaver", "chomping at the bit"], jazz: ["all a-tingle", "hot diggity"], tier: 0 },
  // --- people & things ---
  { a: "friend", o: ["friend", "companion", "comrade", "confidant", "bosom friend", "ally", "good friend", "my friend", "friends"],
    genalpha: ["fam", "my homie", "the homies"], genz: ["fam", "bestie", "my dawg"], millennial: ["my bestie", "the squad"], genx: ["my bud", "the gang"], boomer: ["my pal", "old buddy"], jazz: ["my pal", "ol' chum"], tier: 0 },
  { a: "enemy", o: ["enemy", "foe", "rival", "villain", "adversary", "traitor", "knave", "scoundrel"],
    genalpha: ["opp", "the opps"], genz: ["my opp", "main hater"], millennial: ["nemesis"], genx: ["that jerk"], boomer: ["that no-good rascal"], jazz: ["that heel", "that rat"], tier: 0 },
  { a: "money", o: ["money", "gold", "coin", "crowns", "ducats", "wealth", "riches", "payment", "purse", "treasure"],
    genalpha: ["bread", "bands"], genz: ["the bag", "bands", "racks"], millennial: ["cheddar", "funds"], genx: ["dough", "cash money"], boomer: ["moolah", "the green"], jazz: ["clams", "simoleons", "the mazuma"], tier: 0 },
  { a: "food", o: ["food", "feast", "meal", "banquet", "victuals", "dinner", "supper", "bread", "meat", "fare"],
    genalpha: ["grub", "a snack and a half"], genz: ["eats", "the munchies"], millennial: ["nom noms", "sammies"], genx: ["grub", "chow"], boomer: ["vittles", "fixin's"], jazz: ["the spread", "grub"], tier: 0 },
  { a: "party", o: ["party", "revels", "revelry", "merriment", "festivity", "banquet", "masque", "carouse", "revel"],
    genalpha: ["function", "a function fr"], genz: ["the function", "a kickback"], millennial: ["a shindig", "hangouts"], genx: ["a bash", "a kegger"], boomer: ["a wingding", "a hootenanny"], jazz: ["a clambake", "a petting party"], tier: 0 },
  { a: "vibe", o: ["mood", "atmosphere", "feeling", "air", "temper", "disposition"],
    genalpha: ["vibe", "the vibes"], genz: ["vibe", "the whole vibe"], millennial: ["energy", "vibes"], genx: ["mood", "head space"], boomer: ["ambience"], jazz: ["the atmosphere, see"], tier: 0 },
  { a: "home", o: ["home", "house", "dwelling", "abode", "lodging", "castle"],
    genalpha: ["the crib", "home base"], genz: ["the crib", "home fr"], millennial: ["my place", "the pad"], genx: ["the pad"], boomer: ["the homestead"], jazz: ["the flat"], tier: 0 },
  { a: "clothes", o: ["clothes", "garments", "attire", "raiment", "garb", "doublet", "apparel", "dress", "costume"],
    genalpha: ["the fit", "drip"], genz: ["fit", "the drip", "fit check"], millennial: ["outfit", "ootd"], genx: ["threads"], boomer: ["glad rags", "getup"], jazz: ["glad rags", "the glad rags"], tier: 0 },
  { a: "girl", o: ["maid", "maiden", "wench", "lass", "damsel", "young lady", "girl"],
    genalpha: ["shorty", "shawty"], genz: ["shawty", "the girlie"], millennial: ["that girl"], genx: ["that chick"], boomer: ["that young lady"], jazz: ["a doll", "a sheba"], tier: 0 },
  { a: "guy", o: ["fellow", "chap", "gentleman", "youth", "stripling", "lad", "boy", "guy", "man"],
    genalpha: ["that homie", "bruh over there"], genz: ["that guy fr", "dude"], millennial: ["that dude", "bro"], genx: ["that dude", "that guy"], boomer: ["that fella"], jazz: ["that sheik", "that joe"], tier: 0 },
  { a: "old-person", o: ["old man", "ancient", "greybeard", "old woman", "crone", "aged"],
    genalpha: ["an elder fr", "fossil"], genz: ["an elder", "ancient fr"], millennial: ["ancient one"], genx: ["old timer"], boomer: ["an elder statesman"], jazz: ["an old geezer"], tier: 0 },
  { a: "sword", o: ["sword", "blade", "rapier", "steel", "weapon", "dagger", "dagger's point"],
    genalpha: ["the shank", "cold steel fr"], genz: ["the blade fr", "the shank"], millennial: ["cold steel"], genx: ["the steel"], boomer: ["the trusty blade"], jazz: ["the chiv"], tier: 0 },
  { a: "ghost", o: ["ghost", "spirit", "phantom", "apparition", "spectre", "shade", "sprite"],
    genalpha: ["a whole ghost fr", "spook material"], genz: ["an actual ghost", "ghost energy"], millennial: ["a spooky ghost"], genx: ["a spook"], boomer: ["a haint", "a spook"], jazz: ["a spook, see"], tier: 0 },
  { a: "drink", o: ["drink", "ale", "wine", "sack", "liquor", "beverage", "draught", "potion"],
    genalpha: ["sips", "a bevvy"], genz: ["a bev", "hydration"], millennial: ["bevvies", "sips"], genx: ["a cold one"], boomer: ["a snort", "a nip"], jazz: ["giggle water", "hooch"], tier: 0 },
  // --- actions ---
  { a: "go", o: ["go", "depart", "leave", "begone", "away", "hence", "get thee gone", "get thee hence", "exit", "i must go", "i take my leave", "let us go", "come away"],
    genalpha: ["bounce", "skrrt off"], genz: ["bounce", "dip", "deuces"], millennial: ["roll out", "peel out"], genx: ["book it", "split"], boomer: ["skedaddle", "hit the road"], jazz: ["23 skidoo", "blow this joint"], tier: 0 },
  { a: "come", o: ["come", "approach", "draw near", "come hither", "hither", "advance", "attend"],
    genalpha: ["pull up", "slide thru"], genz: ["pull up", "come thru"], millennial: ["swing by"], genx: ["get over here"], boomer: ["mosey on over"], jazz: ["hop on over, see"], tier: 0 },
  { a: "look", o: ["look", "behold", "lo", "see", "observe", "mark", "behold ye", "lo and behold", "look upon", "look you"],
    genalpha: ["peep this", "look at this fr"], genz: ["peep this", "look at this"], millennial: ["check this out"], genx: ["check it out"], boomer: ["feast your eyes"], jazz: ["get a load of this"], tier: 0 },
  { a: "listen", o: ["listen", "hark", "hear me", "hearken", "attend", "give ear", "lend an ear"],
    genalpha: ["listen up fr", "yo listen"], genz: ["listen up", "hear me out"], millennial: ["ok so listen"], genx: ["listen up"], boomer: ["now listen here"], jazz: ["listen, see"], tier: 0 },
  { a: "wait", o: ["wait", "stay", "tarry", "hold", "abide", "wait a while", "bide"],
    genalpha: ["hold on a sec fr", "chill"], genz: ["hold up", "wait a min"], millennial: ["hang on a sec"], genx: ["hang on"], boomer: ["hold your horses"], jazz: ["hold the phone"], tier: 0 },
  { a: "die", o: ["die", "death", "perish", "expire", "give up the ghost", "slain", "kill", "dead", "murdered", "deadly"],
    genalpha: ["unalive", "get unalived"], genz: ["unalive", "RIP fr"], millennial: ["bite the dust"], genx: ["bite it", "croak"], boomer: ["kick the bucket", "meet one's maker"], jazz: ["rub out", "croak"], tier: 0 },
  { a: "sleep", o: ["sleep", "slumber", "rest", "nap", "repose", "drowse"],
    genalpha: ["catch some z's", "nap time fr"], genz: ["crash", "catch some zzzs"], millennial: ["hit the hay"], genx: ["crash", "sack out"], boomer: ["saw some logs"], jazz: ["hit the hay"], tier: 0 },
  { a: "eat", o: ["eat", "feed", "dine", "sup", "consume", "devour"],
    genalpha: ["munch", "snack on"], genz: ["munch", "go ham on food"], millennial: ["nom", "chow down"], genx: ["chow down", "scarf"], boomer: ["tuck in", "dig in"], jazz: ["dig in, see"], tier: 0 },
  { a: "work", o: ["work", "labor", "toil", "drudge", "travail", "endeavor"],
    genalpha: ["grind", "the grind"], genz: ["grind", "secure the bag"], millennial: ["the hustle", "adulting"], genx: ["the daily grind"], boomer: ["honest day's work"], jazz: ["the salt mines"], tier: 0 },
  { a: "kiss", o: ["kiss", "smooch", "embrace", "a buss", "kisses"],
    genalpha: ["a lil smooch", "smooches"], genz: ["smooch", "a kiss fr"], millennial: ["smooches"], genx: ["a smooch"], boomer: ["a little kiss"], jazz: ["a spoon", "a smooch"], tier: 0 },
  { a: "cheat", o: ["cheat", "swindle", "deceive", "defraud", "cozen", "con", "gull", "beguile", "hoodwink"],
    genalpha: ["finesse", "scam"], genz: ["finesse", "scam", "cap on"], millennial: ["swindle"], genx: ["rip off"], boomer: ["bamboozle", "hornswoggle"], jazz: ["bunco", "take for a ride"], tier: 0 },
  { a: "talk", o: ["speak", "talk", "say", "utter", "declare", "speaketh", "tell", "discourse", "converse"],
    genalpha: ["yap", "spittin'"], genz: ["yap", "spill"], millennial: ["chat"], genx: ["rap", "shoot the breeze"], boomer: ["jaw", "chinwag"], jazz: ["chin", "gas"], tier: 0 },
  // --- intensified verdicts ---
  { a: "amazing", o: ["amazing", "astonishing", "marvelous", "wondrous", "miraculous", "prodigious", "admirable", "passing strange"],
    genalpha: ["mind-blowing fr", "actually insane"], genz: ["insane", "unreal fr"], millennial: ["mind-blown emoji energy"], genx: ["mind-blowing"], boomer: ["the bee's knees", "a marvel"], jazz: ["the cat's whiskers"], tier: 0 },
  { a: "loser", o: ["loser", "wretch", "miscreant", "villain", "knave", "varlet", "rogue", "rascal", "scoundrel", "caitiff", "poltroon", "blackguard"],
    genalpha: ["an L", "a whole L"], genz: ["an L", "fumbled the bag"], millennial: ["a hot mess"], genx: ["a dork", "a loser"], boomer: ["a deadbeat", "a good-for-nothing"], jazz: ["a flat tire", "a hoofer"], tier: 0 },
  { a: "king", o: ["king", "monarch", "sovereign", "majesty", "your majesty", "royal", "crown"],
    genalpha: ["the king fr", "royalty"], genz: ["the king", "royalty fr"], millennial: ["the crown"], genx: ["the big cheese"], boomer: ["his majesty"], jazz: ["the big noise"], tier: 0 },
  { a: "queen", o: ["queen", "sovereign lady", "your grace", "royal lady", "her majesty"],
    genalpha: ["the queen fr", "royalty"], genz: ["the queen", "an icon"], millennial: ["queen energy"], genx: ["the queen bee"], boomer: ["her majesty"], jazz: ["a regal doll"], tier: 0 },
  { a: "snitch", o: ["inform", "tattle", "betray", "reveal", "tattle-tale", "betrayer", "informer", "tell on", "telltale"],
    genalpha: ["snitch fr", "telling"], genz: ["snitch", "rat out"], millennial: ["tattle"], genx: ["rat out", "squeal"], boomer: ["tattletale"], jazz: ["squeal", "sing"], tier: 0 },
  { a: "fake", o: ["fake", "false", "counterfeit", "sham", "pretend", "feigned", "forged", "deceitful", "dishonest"],
    genalpha: ["fake fr", "a whole cap"], genz: ["sus", "fake af"], millennial: ["phony baloney"], genx: ["bogus", "a poser"], boomer: ["phony"], jazz: ["a four-flusher"], tier: 1, n: "fake" },
  { a: "fight", o: ["fight", "duel", "combat", "brawl", "fray", "quarrel", "strife", "battle", "affray"],
    genalpha: ["squabble up", "beef"], genz: ["throw hands", "beef"], millennial: ["throw down"], genx: ["throw down"], boomer: ["a scrap", "a donnybrook"], jazz: ["a rumpus", "a brannigan"], tier: 0 },
  { a: "drunk", o: ["drunk", "drunken", "inebriated", "in my cups", "besotted", "tipsy"],
    genalpha: ["wasted fr", "lit"], genz: ["lit", "turnt"], millennial: ["buzzed"], genx: ["three sheets"], boomer: ["three sheets to the wind", "soused"], jazz: ["lit up", "ossified", "spifflicated"], tier: 0 },
  { a: "boring", o: ["boring", "tedious", "dull", "wearisome", "tiresome", "flat", "stale"],
    genalpha: ["dry", "a snooze fr"], genz: ["dry", "a yawn"], millennial: ["meh", "a snoozefest"], genx: ["a snooze"], boomer: ["dull as dishwater"], jazz: ["flat as a pancake"], tier: 0 },
  { a: "rich", o: ["rich", "wealthy", "prosperous", "opulent", "well-lined"],
    genalpha: ["rich rich", "stacked fr"], genz: ["stacked", "balling"], millennial: ["loaded"], genx: ["rolling in it"], boomer: ["well-heeled", "in the chips"], jazz: ["the big butter-and-egg man"], tier: 0 },
  { a: "poor", o: ["poor", "beggarly", "indigent", "needy", "destitute", "impoverished"],
    genalpha: ["broke fr", "down bad financially"], genz: ["broke", "no bag"], millennial: ["broke af"], genx: ["flat broke"], boomer: ["down and out", "hard up"], jazz: ["on the rocks"], tier: 1, n: "poor" },
  // --- shakespearean function words with era flavors ---
  { a: "indeed", o: ["forsooth", "marry", "by my troth", "in faith", "i' faith", "verily", "indeed", "certainly", "assuredly"],
    genalpha: ["ong", "no cap"], genz: ["no cap", "fr"], millennial: ["for real"], genx: ["no doubt"], boomer: ["sure as shootin'"], jazz: ["and how"], tier: 0 },
  { a: "why", o: ["wherefore", "why", "for what cause", "wherefore art thou"],
    genalpha: ["why tho", "why fr"], genz: ["why tho"], millennial: ["but why"], genx: ["how come"], boomer: ["for what earthly reason"], jazz: ["what for"], tier: 0 },
  { a: "oh-no", o: ["alas", "alack", "oh woe", "woe is me", "woe", "out upon it", "o me", "ay me", "welladay", "fie"],
    genalpha: ["rip", "we're so cooked"], genz: ["rip", "we're doomed fr"], millennial: ["welp"], genx: ["great, just great"], boomer: ["oh for crying out loud", "well I'll be"], jazz: ["oh brother", "phooey"], tier: 0 },
  { a: "oh-wow", o: ["zounds", "sdeath", "what a sight", "marvel", "by heaven", "o brave new world", "'swounds", "gadzooks", "marry and shall"],
    genalpha: ["yo???", "omg fr"], genz: ["omg", "WAIT"], millennial: ["shut up!", "get out!"], genx: ["whoa", "get out"], boomer: ["well I'll be a monkey's uncle", "land sakes"], jazz: ["hot dog", "great guns"], tier: 1, n: "amazing" },
  { a: "curse-light", o: ["a plague", "plague on", "a pox", "the devil take", "damn", "cursed", "curses", "fie upon"],
    genalpha: ["ugh fr", "cursed energy"], genz: ["cursed", "big yikes"], millennial: ["ugh, the worst"], genx: ["that sucks"], boomer: ["darn it all", "dadgummit"], jazz: ["aw nuts", "phooey"], tier: 1, n: "curse" },
  { a: "insult-you", o: ["thou art a knave", "villain", "thou art a villain", "wretch", "thou wretch", "thou art base"],
    genalpha: ["you're such an L", "npc behavior"], genz: ["you're so cooked", "you're a whole clown"], millennial: ["you're the worst"], genx: ["you're such a tool"], boomer: ["you no-good so-and-so"], jazz: ["you're a heel, see"], tier: 0 },
  // --- frequent dramatic speech ---
  { a: "question", o: ["question", "the question", "matter at hand", "query"],
    genalpha: ["the q fr", "the real q"], genz: ["the real question", "the q"], millennial: ["the big Q"], genx: ["the question, duh"], boomer: ["the sixty-four-dollar question"], jazz: ["the $64 question, see"], tier: 0 },
  { a: "suffer", o: ["suffer", "endure", "bear", "suffering", "pain", "agony", "torment", "the slings and arrows"],
    genalpha: ["eat the hits fr", "take the Ls", "took the Ls"], genz: ["take the Ls fr", "grill through it", "took the Ls fr", "taking the Ls"], millennial: ["power through"], genx: ["grin and bear it"], boomer: ["grin and bear it"], jazz: ["grin and bear it, see"], tier: 0 },
  { a: "luck", o: ["fortune", "luck", "chance", "fate", "destiny", "lot", "fortune's", "star-crossed"],
    genalpha: ["the rng", "fate fr"], genz: ["the universe fr", "karma fr"], millennial: ["karma", "the universe"], genx: ["the luck of the draw"], boomer: ["kismet"], jazz: ["the breaks, see"], tier: 0 },
  { a: "trouble", o: ["trouble", "troubles", "difficulty", "strife", "conflict", "a sea of troubles", "misfortune", "adversity"],
    genalpha: ["beef fr", "drama"], genz: ["drama fr", "the beef"], millennial: ["drama"], genx: ["a mess"], boomer: ["hot water"], jazz: ["a jam", "the soup"], tier: 0 },
  { a: "want", o: ["want", "desire", "wish", "long for", "crave", "yearn", "covet", "hunger for"],
    genalpha: ["want so bad fr", "need"], genz: ["want so bad", "need fr"], millennial: ["really want"], genx: ["jonesing for"], boomer: ["hankering after"], jazz: ["got a yen for"], tier: 0 },
  { a: "give", o: ["give", "bestow", "grant", "yield", "bestow upon", "present"],
    genalpha: ["hand it over", "slide me"], genz: ["run me that", "give it up"], millennial: ["fork over"], genx: ["hand over", "give up the goods"], boomer: ["fork over"], jazz: ["cough it up, see"], tier: 0 },
  { a: "take", o: ["take", "seize", "take up", "take arms", "snatch", "lay hold"],
    genalpha: ["snatch fr", "grab"], genz: ["snatch", "grab fr"], millennial: ["grab"], genx: ["take by force"], boomer: ["lay hands on"], jazz: ["snatch, see"], tier: 0 },
  { a: "win", o: ["win", "victory", "triumph", "prevail", "conquer", "vanquish"],
    genalpha: ["secure the dub", "big W"], genz: ["dub", "took the W"], millennial: ["nailed it"], genx: ["crushed it"], boomer: ["won fair and square"], jazz: ["came out on top, see"], tier: 0 },
  { a: "lose", o: ["lose", "defeat", "loss", "fall", "be defeated"],
    genalpha: ["took the L", "big L"], genz: ["took an L", "L fr"], millennial: ["ate it"], genx: ["blew it"], boomer: ["lost my shirt"], jazz: ["took a bath"], tier: 0 },
  { a: "alone", o: ["alone", "solitary", "by myself", "solitude", "lonely", "forsaken", "desolate", "left alone"],
    genalpha: ["on my lonesome fr", "solo dolo"], genz: ["on my lonely", "solo dolo"], millennial: ["me time"], genx: ["flying solo"], boomer: ["all by my lonesome"], jazz: ["high and dry, see"], tier: 0 },
  { a: "together", o: ["together", "united", "as one", "side by side", "joined", "allied"],
    genalpha: ["squad up", "together fr"], genz: ["link up", "we ride together"], millennial: ["team up"], genx: ["stick together"], boomer: ["in this together"], jazz: ["in cahoots", "thick as thieves"], tier: 0 },
  { a: "secret", o: ["secret", "secrets", "hidden", "privy", "concealed", "covert", "private", "i'll not tell"],
    genalpha: ["on the low low", "keep it on the dl fr"], genz: ["on the low", "keep it lowkey"], millennial: ["on the DL"], genx: ["on the QT", "mum's the word"], boomer: ["hush-hush"], jazz: ["on the q.t., see"], tier: 0 },
  { a: "jealous", o: ["jealous", "envy", "envious", "jealousy", "green-eyed", "the green-eyed monster"],
    genalpha: ["pressed", "mad jealous fr"], genz: ["pressed", "jealous fr"], millennial: ["jealous much"], genx: ["green with envy"], boomer: ["fit to be tied with envy"], jazz: ["green as grass"], tier: 0 },
  { a: "new", o: ["new", "novel", "fresh", "strange", "unfamiliar", "the new"],
    genalpha: ["brand new fr", "fresh out"], genz: ["fresh", "brand new"], millennial: ["shiny and new"], genx: ["fresh from the wrapper"], boomer: ["brand-spankin'-new"], jazz: ["newfangled"], tier: 0 },
  { a: "old", o: ["old", "ancient", "aged", "antique", "time-worn", "long ago", "olden"],
    genalpha: ["ancient fr", "from the stone age"], genz: ["dusty", "old af"], millennial: ["old-school"], genx: ["antique"], boomer: ["long in the tooth"], jazz: ["from the ark"], tier: 0 },
  { a: "proud", o: ["proud", "boastful", "vaunting", "glory in", "take pride", "self-satisfied"],
    genalpha: ["flexing", "flexing on 'em"], genz: ["flexing", "big flex"], millennial: ["humble bragging"], genx: ["pleased as punch"], boomer: ["proud as a peacock"], jazz: ["high-hat"], tier: 0 },
  { a: "honor", o: ["honor", "honour", "reputation", "glory", "credit", "good name", "renown"],
    genalpha: ["mad respect", "respect fr"], genz: ["mad respect"], millennial: ["street cred"], genx: ["props"], boomer: ["good name, I tell ya"], jazz: ["on the level, see"], tier: 0 },
  { a: "promise", o: ["promise", "vow", "pledge", "swear", "oath", "give my word", "upon my honor", "plight my troth"],
    genalpha: ["pinky promise fr", "i swear ong"], genz: ["pinky swear", "i promise fr"], millennial: ["pinky promise"], genx: ["cross my heart"], boomer: ["word of honor", "shake on it"], jazz: ["cross my heart, see"], tier: 0 },
  { a: "lose-it", o: ["break my heart", "heartbroken", "crushed", "devastated", "broken-hearted"],
    genalpha: ["so cooked rn", "rip my heart"], genz: ["shattered fr"], millennial: ["totally crushed"], genx: ["gutted"], boomer: ["plumb broke my heart"], jazz: ["blue as blazes"], tier: 0 },
  { a: "now", o: ["now", "immediately", "forthwith", "at once", "anon", "presently", "here and now", "incontinent"],
    genalpha: ["rn", "right now fr"], genz: ["rn", "as we speak fr"], millennial: ["like, now"], genx: ["right this second"], boomer: ["this instant"], jazz: ["on the spot"], tier: 0 },
  { a: "soon", o: ["soon", "shortly", "anon", "ere long", "presently", "before long", "betimes"],
    genalpha: ["in a min", "soon rn"], genz: ["soon fr"], millennial: ["in a bit"], genx: ["in a jiffy"], boomer: ["lickety-split", "directly"], jazz: ["in two shakes"], tier: 0 },
  { a: "flee", o: ["flee", "escape", "run away", "fly", "take flight", "make off", "abscond", "depart in haste"],
    genalpha: ["bounce tf out", "dip fr"], genz: ["dip", "make a run for it fr"], millennial: ["bail"], genx: ["jet"], boomer: ["high-tail it"], jazz: ["take it on the lam", "lamster"], tier: 0 },
  { a: "hide", o: ["hide", "conceal", "cloak", "shroud", "keep hidden", "withdraw"],
    genalpha: ["go ghost", "lay low fr"], genz: ["hide out", "keep it lowkey"], millennial: ["lay low"], genx: ["hole up"], boomer: ["hole up", "keep out of sight"], jazz: ["lay low, see", "take a powder"], tier: 0 },
  { a: "eyes", o: ["eyes", "eyne", "orbs", "gaze", "mine eyes", "thine eyes"],
    genalpha: ["the peepers fr", "eyeballs"], genz: ["the peepers"], millennial: ["baby blues"], genx: ["eyes so blue"], boomer: ["peepers"], jazz: ["lamps", "the old peepers"], tier: 0 },
  { a: "face", o: ["face", "visage", "countenance", "features", "complexion"],
    genalpha: ["the mug fr", "facecard"], genz: ["face card", "the facecard"], millennial: ["mug"], genx: ["mug"], boomer: ["kisser"], jazz: ["mug", "pan"], tier: 0 },
  { a: "no-more", o: ["no longer", "not any longer", "nevermore", "no more"],
    genalpha: ["no more fr", "never again rn"], genz: ["no more fr", "not anymore"], millennial: ["never again"], genx: ["no more of that"], boomer: ["nevermore", "not another bit"], jazz: ["no more, see"], tier: 0 },
  { a: "welcome", o: ["welcome", "well met indeed", "welcome hither", "be welcome"],
    genalpha: ["welcome to the squad", "welcome fr"], genz: ["welcome to the fam"], millennial: ["so glad you're here"], genx: ["welcome aboard"], boomer: ["right neighborly of you to come"], jazz: ["a warm welcome, see"], tier: 0 },
];

// Neutral fallbacks per anchor (used when the entry tier exceeds the classroom filter)
export const NEUTRAL = Object.fromEntries(LEXICON.map((e) => [e.a, e.o[0]]));
